server.port=8089
user.service.message= User service is running from Config server

spring.application.name=UserService
management.tracing.sampling.probability=1.0
management.zipkin.tracing.endpoint=http://localhost:9411/api/v2/spans

spring.datasource.username=root
spring.datasource.password={cipher}?782a27501baa50210737d4dbbb87a315cc0f25a3ba6935361267ceabb48fb99a
