server.port=8089
user.service.message= User service is running from Config server

spring.application.name=UserService
management.tracing.sampling.probability=1.0
management.zipkin.tracing.endpoint=http://localhost:9411/api/v2/spans

spring.datasource.username=root
spring.datasource.password={cipher}?5fa8c91b1c6ff8243cd6d54f38b5d6e6899e243ebbb3b9d5ca9adb9ff84f01c1
